"""empty message

Revision ID: adcd0b5727de
Revises: 442a5f11e8c8
Create Date: 2019-02-05 17:14:00.043928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adcd0b5727de'
down_revision = '442a5f11e8c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('role_id', sa.Integer(), nullable=True))
    op.drop_constraint('employees_department_id_fkey', 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(None, 'employees', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key('employees_department_id_fkey', 'employees', 'roles', ['department_id'], ['id'])
    op.drop_column('employees', 'role_id')
    # ### end Alembic commands ###
